### ISSUE TITLE
Getting Error while Publishing HTML document

### ISSUE THREAD

**Issue by manojmsrit** [doorstop-dev/doorstop#434]
I am getting this below error when I try to publish "SRD" document as HTML document. Could anybody please try to take a look at it and suggest me regarding this. Thank you.

```
(base) MANOJs-MacBook-Air:vscode-remote-try-python manojdeshpande$ python doorstop/cli/main.py publish  SRD one.html
building tree...
publishing document SRD to '/Users/manojdeshpande/vscode-remote-try-python/one.html'...
Successfuly imported extension module "markdown.extensions.extra".
Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
Successfully loaded extension "markdown.extensions.footnotes.FootnoteExtension".
Successfully loaded extension "markdown.extensions.attr_list.AttrListExtension".
Successfully loaded extension "markdown.extensions.def_list.DefListExtension".
Successfully loaded extension "markdown.extensions.tables.TableExtension".
Successfully loaded extension "markdown.extensions.abbr.AbbrExtension".
Successfully loaded extension "markdown.extensions.extra.ExtraExtension".
Successfuly imported extension module "markdown.extensions.sane_lists".
Successfully loaded extension "markdown.extensions.sane_lists.SaneListExtension".
Successfuly imported extension module "mdx_outline".
Successfully loaded extension "mdx_outline.OutlineExtension".
Traceback (most recent call last):
  File "doorstop/cli/main.py", line 516, in <module>
    main()
  File "doorstop/cli/main.py", line 179, in main
    success = function(args, os.getcwd(), parser.error)
  File "./doorstop/cli/commands.py", line 574, in run_publish
    document, path, ext, template=args.template, **kwargs
  File "./doorstop/core/publisher.py", line 94, in publish
    common.write_lines(lines, path2)
  File "./doorstop/common.py", line 162, in write_lines
    for line in lines:
  File "./doorstop/core/publisher.py", line 227, in publish_lines
    yield from gen(obj, **kwargs)
  File "./doorstop/core/publisher.py", line 513, in _lines_html
    body = markdown.markdown(text, extensions=extensions)
  File "/Users/manojdeshpande/miniconda3/lib/python3.6/site-packages/markdown/core.py", line 390, in markdown
    md = Markdown(**kwargs)
  File "/Users/manojdeshpande/miniconda3/lib/python3.6/site-packages/markdown/core.py", line 100, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/Users/manojdeshpande/miniconda3/lib/python3.6/site-packages/markdown/core.py", line 126, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/Users/manojdeshpande/miniconda3/lib/python3.6/site-packages/markdown/core.py", line 166, in build_extension
    module = importlib.import_module(ext_name)
  File "/Users/manojdeshpande/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mdx_math'
```

Regards,
Manoj

**Comment by sebhub** [comment]
> (base) MANOJs-MacBook-Air:vscode-remote-try-python manojdeshpande$ python doorstop/cli/main.py publish  SRD one.html

I am not sure if this is a valid way to use doorstop. I would install doorstop via pip:

https://doorstop.readthedocs.io/en/latest/#installation

**Comment by neerdoc** [comment]
@manojmsrit feel free to close this issue if you feel that your question has been answered!
