### ISSUE TITLE
`six` package not a dependency

### ISSUE THREAD

**Issue by Spenser309** [doorstop-dev/doorstop#444]
Hi,

Looks like the `six` package is not identified as a dependency.

```
➜  products doorstop --help
Traceback (most recent call last):
  File "/usr/local/bin/doorstop", line 5, in <module>
    from doorstop.cli.main import main
  File "/usr/local/lib/python3.7/site-packages/doorstop/__init__.py", line 8, in <module>
    from doorstop.core import (
  File "/usr/local/lib/python3.7/site-packages/doorstop/core/publisher.py", line 12, in <module>
    from plantuml_markdown import PlantUMLMarkdownExtension
  File "/usr/local/lib/python3.7/site-packages/plantuml_markdown.py", line 64, in <module>
    from plantuml import PlantUML
  File "/usr/local/lib/python3.7/site-packages/plantuml.py", line 13, in <module>
    import six
ModuleNotFoundError: No module named 'six'
➜  products pip3 install six
Collecting six
  Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Installing collected packages: six
Successfully installed six-1.13.0
➜  products doorstop --help
usage: doorstop [-h] [-j PATH] [--server HOST] [--port NUMBER] [-f] [-V]
                [-v | -q] [-F] [-r] [-L] [-R] [-C] [-Z] [-S] [-W] [-s PREFIX]
                [-w] [-e]
                <command> ...

Requirements management using version control.
```

**Comment by jacebrowning** [comment]
The `doorstop=2.1` also broken due to https://github.com/dougn/python-plantuml/issues/11.

**Comment by jacebrowning** [comment]
This should be fixed now: https://pypi.org/project/doorstop/2.1.1/
