### ISSUE TITLE
How to use links?

### ISSUE THREAD

**Issue by smattheis** [doorstop-dev/doorstop#499]
Thanks for providing and maintaining this great project. I really like the philosophy and clean style of implementation and documentation. I'm really new to doorstop and I'm trying to model a use case that I need for a project.

The use case is that I want to keep track of requirement dependencies. My understanding was that `links` can be used for modeling such dependencies. However, I could not find a way to get it working.

First, I noticed that right from the beginning I get unexplainable warnings: `no links to parent document: REQ`

``` bash
temp$ mkdir doorstop-test
temp$ cd doorstop-test/
doorstop-test$ git init
Initialized empty Git repository in /temp/doorstop-test/.git/
doorstop-test$ doorstop create REQ ./reqs
building tree...
created document: REQ (@/reqs)
doorstop-test$ doorstop create USRREQ ./reqs/user-reqs --parent REQ
building tree...
created document: USRREQ (@/reqs/user-reqs)
doorstop-test$ doorstop create SYSREQ ./reqs/sys-reqs --parent REQ
building tree...
created document: SYSREQ (@/reqs/sys-reqs)
doorstop-test$ doorstop add USRREQ
building tree...
added item: USRREQ001 (@/reqs/user-reqs/USRREQ001.yml)
doorstop-test$ doorstop add USRREQ
building tree...
added item: USRREQ002 (@/reqs/user-reqs/USRREQ002.yml)
doorstop-test$ doorstop add USRREQ
building tree...
added item: USRREQ003 (@/reqs/user-reqs/USRREQ003.yml)
doorstop-test$ doorstop add SYSREQ
building tree...
added item: SYSREQ001 (@/reqs/sys-reqs/SYSREQ001.yml)
doorstop-test$ doorstop add SYSREQ
building tree...
added item: SYSREQ002 (@/reqs/sys-reqs/SYSREQ002.yml)
doorstop-test$ doorstop
building tree...
loading documents...
validating items...
WARNING: REQ: no items
WARNING: USRREQ: USRREQ001: no text
WARNING: USRREQ: USRREQ001: no links to parent document: REQ
WARNING: USRREQ: USRREQ002: no text
WARNING: USRREQ: USRREQ002: no links to parent document: REQ
WARNING: USRREQ: USRREQ003: no text
WARNING: USRREQ: USRREQ003: no links to parent document: REQ
WARNING: SYSREQ: SYSREQ001: no text
WARNING: SYSREQ: SYSREQ001: no links to parent document: REQ
WARNING: SYSREQ: SYSREQ002: no text
WARNING: SYSREQ: SYSREQ002: no links to parent document: REQ

REQ
│   
├── USRREQ
│   
└── SYSREQ

doorstop-test$ doorstop link SYSREQ001 USRREQ001
building tree...
linked items: SYSREQ001 (@/reqs/sys-reqs/SYSREQ001.yml) -> USRREQ001 (@/reqs/user-reqs/USRREQ001.yml)
doorstop-test$ doorstop link SYSREQ001 USRREQ002
building tree...
linked items: SYSREQ001 (@/reqs/sys-reqs/SYSREQ001.yml) -> USRREQ002 (@/reqs/user-reqs/USRREQ002.yml)
doorstop-test$ doorstop link SYSREQ002 USRREQ001
building tree...
linked items: SYSREQ002 (@/reqs/sys-reqs/SYSREQ002.yml) -> USRREQ001 (@/reqs/user-reqs/USRREQ001.yml)
doorstop-test$ doorstop
building tree...
loading documents...
validating items...
WARNING: REQ: no items
WARNING: USRREQ: USRREQ001: no text
WARNING: USRREQ: USRREQ001: no links to parent document: REQ
WARNING: USRREQ: USRREQ002: no text
WARNING: USRREQ: USRREQ002: no links to parent document: REQ
WARNING: USRREQ: USRREQ003: no text
WARNING: USRREQ: USRREQ003: no links to parent document: REQ
WARNING: SYSREQ: SYSREQ001: no text
WARNING: SYSREQ: SYSREQ001: unreviewed changes
WARNING: SYSREQ: SYSREQ002: no text
WARNING: SYSREQ: SYSREQ002: unreviewed changes

REQ
│   
├── USRREQ
│   
└── SYSREQ

```

Second, the "scripting API" seems to provide something like a reverse link search but it does not work as the result of `child_links` is empty:

``` python
doorstop-test$ python
Python 3.8.5 (default, Jul 21 2020, 10:42:08) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import doorstop
>>> tree = doorstop.build()
>>> tree
<Tree REQ <- [ USRREQ, SYSREQ ]>
>>> sysreq1 = tree.find_item('SYSREQ001')
>>> sysreq1
Item('/temp/doorstop-test/reqs/sys-reqs/SYSREQ001.yml')
>>> sysreq1.links
[UID('USRREQ001', stamp='veIi7LzAK7OSJ_wlY0XPXqUXi7K4BBwNoCcss8gl3kU='), UID('USRREQ002', stamp='Rz0zTf8O79_INLD9E3jFofDF-ipGd6qBgO9CS6VRgQE=')]
>>> usrreq1 = tree.find_item('USRREQ001')
>>> usrreq1
Item('/temp/doorstop-test/reqs/user-reqs/USRREQ001.yml')
>>> usrreq1.child_links
[]
>>> 
```

Third, the doorstop-server is not able provide the HTML documents (although this problem may not be related to the linkage issue):

``` bash
doorstop-test$ doorstop-server
[INFO    ] looking for documents in /temp/doorstop-test...
[INFO    ] found document: REQ
[INFO    ] found document: USRREQ
[INFO    ] found document: SYSREQ
[INFO    ] building tree...
[INFO    ] root of the tree: REQ
[INFO    ] added to tree: USRREQ
[INFO    ] added to tree: SYSREQ
[INFO    ] built tree: REQ <- [ USRREQ, SYSREQ ]
[INFO    ] loading the tree...
[INFO    ] loading document REQ's items...
[INFO    ] loading document USRREQ's items...
[INFO    ] loading document SYSREQ's items...
Bottle v0.12.19 server starting up (using WSGIRefServer())...
Listening on http://127.0.0.1:7867/
Hit Ctrl-C to quit.

127.0.0.1 - - [14/Jan/2021 14:06:46] "GET / HTTP/1.1" 200 874
127.0.0.1 - - [14/Jan/2021 14:07:39] "GET /documents/ HTTP/1.1" 200 838
127.0.0.1 - - [14/Jan/2021 14:07:49] "GET /documents/USRREQ HTTP/1.1" 500 755
127.0.0.1 - - [14/Jan/2021 14:07:58] "GET /documents/REQ HTTP/1.1" 500 752

```

<img width="654" alt="CapturFiles-Jan-14-2021_14 07 32" src="https://user-images.githubusercontent.com/7805104/104594916-227fe680-5672-11eb-939f-14a91a296731.png">
<img width="654" alt="CapturFiles-Jan-14-2021_14 07 43" src="https://user-images.githubusercontent.com/7805104/104594937-2b70b800-5672-11eb-9343-3274ddab1e84.png">
<img width="654" alt="CapturFiles-Jan-14-2021_14 07 53" src="https://user-images.githubusercontent.com/7805104/104595002-40e5e200-5672-11eb-9bfa-92913e5b4018.png">

I would appreciate any help. If you need further information please let me know.

**Comment by jacebrowning** [comment]
The `no links to parent document` warning is telling you that a child document (`USRREQ` and `SYSREQ`) have zero items linking to items in the parent document (`REQ`) meaning that the requirements in the parent document cannot possibly be fulfilled.

Do you have a stack trace from the Intern Server Error?

**Comment by smattheis** [comment]
Thanks for your reply. 

1. How can I create a stack trace with the doorstop-server? (I haven't found any debug or verbose mode.)
2. Why are the `child_links` empty?

**Comment by jacebrowning** [comment]
`child_links` contains all links from child documents to the current document. In your example you've linked items in two sibling documents.

I've been able to reproduce the server error on `develop` so I'll see if I can fix that.

**Comment by smattheis** [comment]
I really don't get the linkage concept in doorstop and it appears inconsistent to me: Why can I link items in sibling documents and don't get any error or warning; while the created linkage is then not supported with the functionality that is expected from such linkage, i.e., forward and reverse link lookup?

Can you please explain that to me? I want to understand. (I mean there can be many reasons but I don't see what's the matter here: Am I using it wrong? Is it a design flaw in doorstop that there is no warning/error when linking items from sibling documents? Is the linkage in fact valid but the look up is simply not implemented?)

**Comment by jacebrowning** [comment]
Linking between items in sibling documents is supported but the current implement of `child_links` only searches child documents:

https://github.com/doorstop-dev/doorstop/blob/cb7fd7b4a9c4a78cc02d1df961458f4a9c57cab7/doorstop/core/item.py#L731-L740

Assuming that changing that doesn't break some other functionality. A PR to search all documents would be accepted.

---

> How can I create a stack trace with the doorstop-server? (I haven't found any debug or verbose mode.)

There is a `--debug` flag, which is now documented in the latest release.

**Comment by smattheis** [comment]
Thanks. The error looks like a dependency issue:

<img width="1010" alt="CapturFiles-Jan-15-2021_08 42 15" src="https://user-images.githubusercontent.com/7805104/104695914-bf439200-570d-11eb-8658-32dbc6c403e1.png">

``` bash
Error: 500 Internal Server Error
Sorry, the requested URL 'http://127.0.0.1:7867/documents/USRREQ' caused an error:

Unhandled exception
Exception:
AttributeError("module 'markdown' has no attribute '__version_info__'")
Traceback:
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 929, in _cast
    first = next(iout)
  File "/usr/local/lib/python3.8/site-packages/doorstop/core/publisher.py", line 240, in publish_lines
    yield from gen(obj, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/doorstop/core/publisher.py", line 594, in _lines_html
    body = markdown.markdown(text, extensions=extensions)
  File "/usr/local/lib/python3.8/site-packages/markdown/__init__.py", line 493, in markdown
    md = Markdown(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/markdown/__init__.py", line 158, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/usr/local/lib/python3.8/site-packages/markdown/__init__.py", line 187, in registerExtensions
    ext.extendMarkdown(self, globals())
  File "/usr/local/lib/python3.8/site-packages/plantuml_markdown.py", line 309, in extendMarkdown
    if markdown.__version_info__[0] < 3:
AttributeError: module 'markdown' has no attribute '__version_info__'
```

**Comment by DaPa** [comment]
I think markdown has to be upgraded: for me it comes as an oldish version 2.6.11 when installing doorstop.
I didn't play with python before, so proper fixes should be done by the experts: but temporarily see possible markdown hacks in https://github.com/sevendays/doorhole/issues/2#issuecomment-760196320.
Alternatively hack the plantuml_markdown as per https://github.com/sevendays/doorhole/issues/2#issuecomment-760268886.

**Comment by jacebrowning** [comment]
I've updated the markdown dependency in the latest release: https://pypi.org/project/doorstop/2.1.4/

**Comment by smattheis** [comment]
Thanks, it works for me. Thanks also for the clarification about the linkage. I consider to add the functionality to find forward and backward links. For now I only tried a simple code snippet which works smoothly. 

``` python
(.venv) doorstop-test$ python
Python 3.8.5 (default, Jul 21 2020, 10:42:08) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import doorstop
>>> import networkx as nx
>>> 
>>> tree = doorstop.build()
>>> graph = nx.DiGraph()
>>>
>>> for doc in tree.documents:
...     for item in doc.items:
...         graph.add_node(item.uid.value, doc=str(doc.prefix))
...         for link in item.links:
...             graph.add_edge(item.uid.value, link.value)
... 
>>> list(graph.successors("SYSREQ001"))
['USRREQ001', 'USRREQ002']
>>> list(graph.predecessors("USRREQ001"))
['SYSREQ001', 'SYSREQ002']
>>> quit()
```

However, I would actually like to have that shown in the HTML output which is another issue. I'm closing this one.
