### ISSUE TITLE
Cannot publish item holding special characters in text

### ISSUE THREAD

**Issue by urbasus** [doorstop-dev/doorstop#524]
Getting an error on publishing a document where an item is having special characters:

- Have special characters in item
  - E.g. paste the MIT license into an item, https://mit-license.org/
  - My name has an "á" in it, not quite the same without it
- Publish

Result:

```
$ make hello/hello.md
doorstop publish -m hello
building tree...
Traceback (most recent call last):
  File "/home/andreas/.local/lib/python3.7/site-packages/doorstop/common.py", line 115, in read_text
    return f.read()
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 196: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andreas/.local/bin/doorstop", line 10, in <module>
    sys.exit(main())
  File "/home/andreas/.local/lib/python3.7/site-packages/doorstop/cli/main.py", line 176, in main
    success = function(args, os.getcwd(), parser.error)
  File "/home/andreas/.local/lib/python3.7/site-packages/doorstop/cli/commands.py", line 596, in run_publish
    for line in publisher.publish_lines(document, ext, **kwargs):
  File "/home/andreas/.local/lib/python3.7/site-packages/doorstop/core/publisher.py", line 238, in publish_lines
    yield from gen(obj, **kwargs)
  File "/home/andreas/.local/lib/python3.7/site-packages/doorstop/core/publisher.py", line 330, in _lines_markdown
    for item in iter_items(obj):
  File "/home/andreas/.local/lib/python3.7/site-packages/doorstop/core/types.py", line 652, in iter_items
    if is_document(obj):
  File "/home/andreas/.local/lib/python3.7/site-packages/doorstop/core/types.py", line 628, in is_document
    return hasattr(obj, 'items')
  File "/home/andreas/.local/lib/python3.7/site-packages/doorstop/core/document.py", line 373, in items
    return sorted(i for i in self._iter() if i.active)
  File "/home/andreas/.local/lib/python3.7/site-packages/doorstop/core/document.py", line 373, in <genexpr>
    return sorted(i for i in self._iter() if i.active)
  File "/home/andreas/.local/lib/python3.7/site-packages/doorstop/core/base.py", line 178, in wrapped
    self.load()
  File "/home/andreas/.local/lib/python3.7/site-packages/doorstop/core/item.py", line 249, in load
    text = self._read(self.path)
  File "/home/andreas/.local/lib/python3.7/site-packages/doorstop/core/base.py", line 260, in _read
    return common.read_text(path)
  File "/home/andreas/.local/lib/python3.7/site-packages/doorstop/common.py", line 118, in read_text
    raise DoorstopError(msg)
```

**Comment by urbasus** [comment]
Possibly related: https://stackoverflow.com/questions/12468179/unicodedecodeerror-utf8-codec-cant-decode-byte-0x9c

**Comment by jacebrowning** [comment]
The fix for this should be available here: https://pypi.org/project/doorstop/3.0b3/
