### ISSUE TITLE
Install fails because of pyyaml

### ISSUE THREAD

**Issue by MartyLake** [doorstop-dev/doorstop#604]
Hi,
I tried to install with `python3 -m pip install doorstop` but it fails because of pyyaml.
I tried to run from sources using `poetry shell` then `poetry install` but I get the same error, copied below:

```
  • Installing pyyaml (5.4.1): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  /private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
  !!

          ********************************************************************************
          The license_file parameter is deprecated, use license_files instead.

          By 2023-Oct-30, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.

          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************

  !!
    parsed = self.parsers.get(option_name, lambda x: x)(value)
  running egg_info
  writing lib3/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib3/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/opt/homebrew/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/homebrew/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 271, in <module>
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
      super().run_command(command)
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 318, in run
      self.find_sources()
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
      mm.run()
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 548, in run
      self.add_defaults()
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
      sdist.add_defaults(self)
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
      super().add_defaults()
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<string>", line 201, in get_source_files
    File "/private/var/folders/qh/5q_cgpnd3fv05hd_9bmn7m180000gp/T/tmpl7x87l6d/.venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources



  at /opt/homebrew/lib/python3.11/site-packages/poetry/installation/chef.py:147 in _prepare
      143│
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│
      146│             if error is not None:
    → 147│                 raise error from None
      148│
      149│             return path
      150│
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pyyaml (5.4.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pyyaml (==5.4.1)"'.

```

**Comment by jacebrowning** [comment]
This should be fixed in this release: https://pypi.org/project/doorstop/2.2.1/
